import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import logoBase64 from '@/assets/cashilLogo.png'; // ✅ pakai langsung base64

// Efek blur lingkaran
function drawBlurredCircle(doc, x, y, baseRadius, baseColor) {
  const opacities = [0.03, 0.02, 0.01];
  const radii = [baseRadius, baseRadius + 6, baseRadius + 12];

  opacities.forEach((opacity, i) => {
    doc.setGState(new doc.GState({ opacity }));
    doc.setFillColor(...baseColor);
    doc.circle(x, y, radii[i], 'F');
  });

  doc.setGState(new doc.GState({ opacity: 1 }));
}

export const exportToPDF = async (transactions) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const user = localStorage.getItem('username') || 'Pengguna Cashil';
  const now = new Date().toLocaleString('id-ID', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const headerHeight = 35;
  const logoSize = 20;
  const paddingLeft = 15;
  const paddingTop = 8;
  const blue = [59, 130, 246];

  // 🔵 Header background
  doc.setFillColor(...blue);
  doc.rect(0, 0, doc.internal.pageSize.width, headerHeight, 'F');

  // 🔵 Logo dan Teks header
  try {
    doc.addImage(logoBase64, 'PNG', paddingLeft, paddingTop, logoSize, logoSize);
  } catch (err) {
    console.warn('Logo gagal ditampilkan:', err);
  }

  const textX = paddingLeft + logoSize + 6;
  let currentY = paddingTop + 4;

  doc.setFont('times', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('Laporan Transaksi', textX, currentY);

  currentY += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text('Track Your Money, Stay Chill', textX, currentY);

  currentY += 6;
  doc.setFontSize(10);
  doc.text(`Pengguna: ${user}`, textX, currentY);

  currentY += 5;
  doc.text(`Dicetak: ${now}`, textX, currentY);

  // 🔵 Watermark tengah
  try {
    const imgWidth = 50;
    const imgHeight = 50;
    const x = (doc.internal.pageSize.width - imgWidth) / 2;
    const y = (doc.internal.pageSize.height - imgHeight) / 2 - 20;

    doc.setGState(new doc.GState({ opacity: 0.1 }));
    doc.addImage(logoBase64, 'PNG', x, y, imgWidth, imgHeight);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(30);
    doc.setTextColor(180, 180, 180);
    doc.text('CASHIL', doc.internal.pageSize.width / 2, y + imgHeight + 10, { align: 'center' });
    doc.setGState(new doc.GState({ opacity: 1 }));
  } catch (err) {
    console.warn('Watermark gagal dimuat:', err);
  }

  // 🔵 Dekorasi lingkaran blur
  drawBlurredCircle(doc, 30, 80, 25, blue);
  drawBlurredCircle(doc, doc.internal.pageSize.width - 30, 120, 30, blue);
  drawBlurredCircle(doc, 50, doc.internal.pageSize.height - 50, 40, blue);
  drawBlurredCircle(doc, doc.internal.pageSize.width - 60, doc.internal.pageSize.height - 100, 35, blue);

  // 🔵 Tabel transaksi
  const tableData = transactions.map((tx, index) => [
    index + 1,
    tx.title,
    new Date(tx.date).toLocaleDateString('id-ID', { year: 'numeric', month: 'short', day: 'numeric' }),
    tx.type === 'income' ? 'Pendapatan' : 'Pengeluaran',
    `Rp${Number(tx.amount).toLocaleString('id-ID')}`
  ]);

  autoTable(doc, {
    startY: headerHeight + 10,
    head: [['#', 'Judul Transaksi', 'Tanggal', 'Jenis', 'Jumlah']],
    body: tableData,
    theme: 'striped',
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: [51, 51, 51],
      lineColor: [230, 230, 230],
      lineWidth: 0.1
    },
    headStyles: {
      fillColor: blue,
      textColor: 255,
      fontStyle: 'bold',
      halign: 'center',
      valign: 'middle',
      fontSize: 10,
      cellPadding: 4
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 12 },
      1: { cellWidth: 60 },
      2: { halign: 'center', cellWidth: 30 },
      3: { halign: 'center', cellWidth: 30 },
      4: { halign: 'right', cellWidth: 40 },
    },
    didDrawPage: function (data) {
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by Cashil • cashil.app | Page ${data.pageNumber}`, 14, doc.internal.pageSize.height - 10);
    }
  });

  doc.save('laporan-transaksi-cashil.pdf');
};
